### ISSUE TITLE
Deleting one author folder does not remove him from Meet the team list on home page.

### ISSUE THREAD

**Issue by chandreshiit** [MyersResearchGroup/myersresearchgroup.github.io#137]
Hi,

I deleted one of the author from the "author" folder. However, it does not delete him on the home page. Though the same can be achieved by removing the "user_group=["researcher"] in index.md file. This is kind of annoying given the fact that if I remove the author folder, it should not list that author on home page. Any solution?

**Comment by cjmyers** [comment]
Are you using our website as a model for you one of your own?

@Fontanapink @JMante1 any comments on this?

**Comment by Fontanapink** [comment]
We are not!

**Comment by chandu8542** [comment]
Yes. I'm using the template of yours.
