### ISSUE TITLE
Standardize the publications

### ISSUE THREAD

**Issue by yu-eric** [MyersResearchGroup/myersresearchgroup.github.io#31]
Some are missing abstracts, etc.

**Comment by JMante1** [comment]
I have done some editing to the publication tags as there was a lack of standardisation that made some of the functionality break.

**Comment by Fontanapink** [comment]
Oh, those tags are assigned automatically. Soon I will re-update all the publications and those tags will be re-generetad! It would be good to write down which publication tags you modified so we can change them again after the import.

**Comment by JMante1** [comment]
Just as a reminder I removed the " from tags e.g. '"synbiohib"' and '"Asynchronous Circuits"' I think the additional double quotes inside the ' is a bug in the conversion script
