### ISSUE TITLE
Add courses to teaching section

### ISSUE THREAD

**Issue by yu-eric** [MyersResearchGroup/myersresearchgroup.github.io#33]

**Comment by cjmyers** [comment]
https://utah.instructure.com/courses/514350 

https://utah.instructure.com/courses/543150 

https://utah.instructure.com/courses/578293

https://utah.instructure.com/courses/476851

https://utah.instructure.com/courses/578294

https://utah.instructure.com/courses/98994

**Comment by JMante1** [comment]
Asynchronous Circuit Design
and Verification of Cyber-Physical Systems are both closed canvas courses (you need to sign in to be able to see them)

**Comment by cjmyers** [comment]
Fixed now
