### ISSUE TITLE
Change home page biography

### ISSUE THREAD

**Issue by yu-eric** [MyersResearchGroup/myersresearchgroup.github.io#35]
Text is outdated and does not match the current website.

**Comment by JMante1** [comment]
This is done by editing the file content/authors/admin/_index.md

**Comment by cjmyers** [comment]
Can you point me to the text in question?

**Comment by JMante1** [comment]
The text currently says: The Genetic Logic Lab is run by Chris Myers. The research in the lab focuses on the interdisciplinary synthetic biology work in the overlap between electrical engineering, mathematical modelling, and genetic biology. Examples of work include: the creation of genetic design automation programs similar to electronic design automation programs for circuit designs, stochastic verification of genetic models, and a repository for storing and sharing genetic constructs.

**Comment by JMante1** [comment]
It should be the very bottom part of the file mentioned above

**Comment by cjmyers** [comment]
This text looks pretty good.  Was @yu-eric referring to our old website text?

**Comment by JMante1** [comment]
Yes, I had made a temporary edit but wasn't sure what exactly you wanted to say.

**Comment by cjmyers** [comment]
I think this is pretty good for now.
